### ISSUE TITLE
install38conf.sh Error in PATH

### ISSUE THREAD

**Issue by GeorgeIoak** [Maschine2501/NR1-UI#1]
In https://github.com/Maschine2501/NR1-UI/blob/master/install38conf.sh#L28 I think you need to remove the ~

Also, in your original install script you created an alias for python3 but i don't see that in your new script

I had used your script when it installed python 3.5.2, do you know of the best way to remove that now that 3.8.5 is installed?

**Comment by Maschine2501** [comment]
@GeorgeIoak Thanks for the advice, I've removed it!

I've noticed that the "alias" to python 3 is not needed.
If you want to use Python 3.8.5 for other things, you may can make an alias for it.
(But beware: In my Testing, the WEB-UI and SSH was often not reachable after installing Python 3.8.5...
I think it came from symlink to Python 3.8.5 instead oft pre-installed 3.4, or OpenSSL... But I can't say which wone to blame...)

Regarding the removal of Python 3.5.2-> I will work on an Uninstaller script the next days... Right now I can only advice to test:
```
sudo make uninstall
``` 
in the python 3.5.2 folder...
But I've not uninstalled anything yet, so this may not work...

**Comment by GeorgeIoak** [comment]
OK, right now I am having some difficulty getting things to run since I installed Python 3.8.5. I've made some other changes so I don't want to wipe out and start over.

SSH still works for me and the WEB-UI come up but I think right now it does not play but I'll do som additional checking and testing.

I don't have anything on the display since upgrading to Python 3.8.5 which I did by manually following your instal38.sh. The service is stopping but oddly this is the error:

```
Sep 20 15:26:38 volumio systemd[1]: nr1ui.service: main process exited, code=exited, status=1/FAILURE
Sep 20 15:26:38 volumio systemd[1]: Unit nr1ui.service entered failed state.
Sep 20 15:34:44 volumio systemd[1]: Starting NR1-UI...
Sep 20 15:34:44 volumio systemd[1]: Started NR1-UI.
Sep 20 15:34:44 volumio nr1ui[1662]: File "/home/volumio/NR1-UI/nr1ui.py", line 845
Sep 20 15:34:44 volumio nr1ui[1662]: global ScrollArtistTag
Sep 20 15:34:44 volumio nr1ui[1662]: ^
Sep 20 15:34:44 volumio nr1ui[1662]: SyntaxError: name 'ScrollArtistTag' is used prior to global declaration
Sep 20 15:34:44 volumio systemd[1]: nr1ui.service: main process exited, code=exited, status=1/FAILURE
Sep 20 15:34:44 volumio systemd[1]: Unit nr1ui.service entered failed state.
```

As a side note if you happen to have the python config module installed `from config.ScreenConfig1322 import*` will fail. If I tested but moving the files in the config directory I was able to import from the REPL during testing and after I uninstalled (`pip3 uninstall config`) I didn't get that error. So you might want to change the config directory name in case some some other code installs the config module.

**Comment by Maschine2501** [comment]
@GeorgeIoak Thanks aggain for the informations!!! ;)

Regarding the nr1ui.service that entered fail state:
Actually there are 3 Versions of the code (i will clean up later...):
1. nr1ui.py -> with the nr1ui.service [Installation](https://github.com/Maschine2501/NR1-UI/wiki/Installation-Steps-(Bash-Script))
   -> This will need Python 3.5.2 to run! See the steps of the [install.sh](https://github.com/Maschine2501/NR1-UI/blob/master/install.sh)
2. nr1ui38.py -> with the nr1ui38.service [Installation](https://github.com/Maschine2501/NR1-UI/wiki/Installation-Steps-(for-Python3.8.5-Version---Bash-Script))
   -> This does not Use Python 3.5.2 anymore, instead it installs Python 3.8.5! See the steps of the [install38.sh](https://github.com/Maschine2501/NR1-UI/blob/master/install38.sh)
3. nr1ui38conf.py -> with the nr1ui38-conf.service [Installation](https://github.com/Maschine2501/NR1-UI/wiki/Installation-Steps-(for-Python3.8.5-Version---Autoconfig-Bash-Script))
   -> Like 2. it uses Python 3.8.5, but here a Auto-Config-Dialog was added to the Installation script, the values are stored in the PreConfiguration.py, to get this running it was needed to make changes in the nr1ui38.py -> this is the reason why there is a nr1ui38conf.py. See the steps of the  [install38conf.sh](https://github.com/Maschine2501/NR1-UI/blob/master/install38conf.sh)

As soon as I safely know that the 3rd variant (nr1ui38conf.py) is running fine, i will remove the other Versions....

The easiest way to solve the problem for you, would be: Make a clean installation (fresh volumio!) and follow the [instructions](https://github.com/Maschine2501/NR1-UI/wiki/Installation-Steps-(for-Python3.8.5-Version---Autoconfig-Bash-Script)). Otherwise it would be tricky to get it running aggain (Remove NR1-UI folder and service, gitclone NR1UI, run the PreConfiguration Script, run the mpd.sh script, activate the .service for nr1ui38-conf....)

The conflict with the "config" module is Gold! I did not mention this! Thanks for the information, I'll change it soon!!

**Comment by Maschine2501** [comment]
@GeorgeIoak To specify what you have to do to get it running (without a new installation:
```
sudo systemctl stop nr1ui.service
sudo systemctl disable nr1ui.service
cd
```
sudo rm -r NR1-UI    ->(WILL DELETE THE WHOLE FOLDER! -> If you got nr1ui38conf.py and PreConfiguration.sh in the NR1-UI Folder, you do not need to do this! 
If You have done the "sudo RM -r..." then make: git clone https://github.com/Maschine2501/NR1-UI.git
```
chmod +x /home/volumio/NR1-UI/nr1ui38-conf.py #

sudo chmod +x NR1-UI/mpd-buffertime.sh

sudo chmod +x NR1-UI/mpd.sh 

sudo chmod +x NR1-UI/PreConfiguration.sh #

sudo bash NR1-UI/PreConfiguration.sh

sudo bash NR1-UI/mpd.sh
```
optional: (Sets a custom buffertime for MPD)

sudo bash NR1-UI/mpd-buffertime.sh
```
sudo cp /home/volumio/NR1-UI/service-files/nr1ui38-conf.service /lib/systemd/system/ 

sudo systemctl daemon-reload

sudo systemctl enable nr1ui38-conf.service

reboot
´´´

**Comment by GeorgeIoak** [comment]
@Maschine2501 Thanks for the details. Yes, I started with your nr1ui.py and Python 3.5.2. Later I looked at install38.sh and manually ran the steps to install Python 3.8.5. It was after doing this that I noticed the troubles (NR1 service errors and volumio not playing any music).
Yesterday I tried uninstalling openSSL and reinstalling Python 3.8.5 without SSL but that didn't go well. I might have missed something something but doing that didn't fix volumio and NR1 gave that new error.

Do you know that volumio will still work with Python 3.8.5? It looked from my research that since volumio is running Jessie it might be difficult to upgrade Python. If you know that volumio works with Python 3.8.5 I'll try your advice here and see if it fixes my issues.

I saw your latest script (install38-conf.sh) but it looked like it was adding configuration during install and the actual installation was still the same as install38.sh and since I was already configured I thought I might not need to use it.

You also have a minor typo in install38.sh and install38-conf.sh. The 2nd [LD_LIBRARY_PATH](https://github.com/Maschine2501/NR1-UI/blob/master/install38conf.sh#L30) is PATh instead of PATH

**Comment by GeorgeIoak** [comment]
```
chmod +x /home/volumio/NR1-UI/nr1ui38-conf.py #

sudo chmod +x NR1-UI/mpd-buffertime.sh

sudo chmod +x NR1-UI/mpd.sh 

sudo chmod +x NR1-UI/PreConfiguration.sh #

sudo bash NR1-UI/PreConfiguration.sh
<<<--- Don't I still need to run install38-conf.sh here?
sudo bash NR1-UI/mpd.sh
```

**Comment by Maschine2501** [comment]
If you have done the main installation steps in it... no.
If not... then yes, run it ;)

**Comment by Maschine2501** [comment]
@GeorgeIoak Sorry, I did not noticed your first answer.
Yes the basic installation steps in install38.sh and install38conf.sh are pretty the same... but I've changed some stuff in the main code.
I#m actually having trouble with the installation... therfore please wait for a moment, until i have fixed everything.
If you've installed the 3.5.2 version before I highhly recomend a clean installation for the 3.8.5 version...

**Comment by GeorgeIoak** [comment]
OK, I'll wait. I did start with 3.5.2 but I'm hoping we'll find a way to recover rather than starting clean. The reason I don't want to start clean is because I have some work done with IR remote support and using a rotary encoder to change volume on my custom board (using a PGA2320) rather than changing the ALSA volume.

Right now I still have Python 3.8.5 installed but I recompiled and installed it without SSL support. I was hoping the problems I had were related to the addition of SSL but that might not be true. Even though I removed and reconfigured Python without SSL support when I ran pip3 it complained that it was installed with SSL support and that SSL was missing. So maybe SSL could still be part of the problem and I really didn't fully recompile Python without SSL support?

**Comment by Maschine2501** [comment]
Status: I fixed my issue with the 3.8.5 Version and changed the "config"-folder name, so that there will be no conflict with a Config-python module.
The next step is: I'll clean up here, the "old" python3.5.2 Version will move to a new repository.
This Respository will only provide the python 3.8.5 Version...

This will take some time. 

@Georgeloak: I think it is not realy possible to assist you with fixing your "half/half" installation here... maybe you could join my discord channel... 
Also I'm very interested in the IR an Volume stuff you did... Maybe you can share it with me, and I'll see if i can integrate it here?

**Comment by GeorgeIoak** [comment]
OK, sounds good. I can test it now. Earlier you mentioned:

_(But beware: In my Testing, the WEB-UI and SSH was often not reachable after installing Python 3.8.5_

Is this problem gone?

**Comment by Maschine2501** [comment]
@GeorgeIoak Sorry for the missunderstanding: My statement was NOT regarding to the code here on Github. These Issues happend while i was figuring out the installation method for python3.8.5 and openssl1.1.1b.

Right now, [this installation steps](https://github.com/Maschine2501/NR1-UI/wiki/Installation-Steps-(for-Python3.8.5-Version---Autoconfig-Bash-Script)) should work just fine, no bugs/malfunctions wit Volumio/webinterface/SSH. (At least with a fresh installation of Volumio... o.O)

**Comment by GeorgeIoak** [comment]
OK, thanks for clarifying. I know right now my system is a bit of a mess so my results might not work but I'm going to try.

- I'm going to disable all of you services and remove the service files
- Delete my NR1-UI directory
- Remove alias and path to Python 3.8.5
- Remove src directory
- reboot
- Then git clone and follow your [steps in this post](https://github.com/Maschine2501/NR1-UI/issues/1#issuecomment-695910727)

**Comment by Maschine2501** [comment]
@GeorgeIoak that should work... i guess... ^^

**Comment by GeorgeIoak** [comment]
Well I did all of the deletions and cleanup. I then rebooted and the volumio UI still does not respond to pressing play. I can navigate songs and change the position in the song so it seems that everything works in the UI except for actually playing a song.
```
volumio@volumio:~$ python3 --version
Python 3.5.2
volumio@volumio:~$
```
So maybe something in the libraries I installed trying to get Python 3.8.5 to work or I've done something else. :(

I might have to do a clean install of volumio and start over but I'll try to install your code and see if by chance fixes things. If I start a live log in volumio (using volumio.local/dev) I see this which doesn't help much:

```
Starting Live Log...
info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetQueue
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: system , getHwuuid
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
info: CoreCommandRouter::volumioPlay
UNSET VOLATILE
info: CoreStateMachine::play index undefined
info: CoreStateMachine::setConsumeUpdateService undefined
info: CorePlayQueue::getTrack 0
info: CoreStateMachine::startPlaybackTimer
info: CorePlayQueue::getTrack 0
info: [1600715933588] ControllerUPNPBrowser::clearAddPlayTrack
```

I'm also seeing some:
```
Sep 21 12:26:21 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
Sep 21 12:26:26 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
Sep 21 12:26:31 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
Sep 21 12:26:36 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
Sep 21 12:26:41 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
Sep 21 12:26:46 volumio volumio[1655]: error: MPD error: Error: connect ECONNREFUSED /run/mpd/socket
```

So maybe this is something that can be fixed. I ran volumio config wizard again but no luck in fixing the problem

**Comment by Maschine2501** [comment]
The "no playback" problem is nearly 100percent caused by mpd...

**Comment by GeorgeIoak** [comment]
Problem solved!
```
volumio@volumio:~$ sudo systemctl status mpd.service -l
● mpd.service - Music Player Daemon
   Loaded: loaded (/lib/systemd/system/mpd.service; enabled)
   Active: failed (Result: start-limit) since Mon 2020-09-21 12:28:08 PDT; 14min ago
     Docs: man:mpd(1)
           man:mpd.conf(5)
  Process: 1395 ExecStart=/usr/bin/mpd --no-daemon (code=exited, status=127)
 Main PID: 1395 (code=exited, status=127)

Sep 21 12:28:08 volumio mpd[1395]: /usr/bin/mpd: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory
Sep 21 12:28:08 volumio systemd[1]: mpd.service: main process exited, code=exited, status=127/n/a
Sep 21 12:28:08 volumio systemd[1]: Failed to start Music Player Daemon.
Sep 21 12:28:08 volumio systemd[1]: Unit mpd.service entered failed state.
Sep 21 12:28:08 volumio systemd[1]: Starting Music Player Daemon...
Sep 21 12:28:08 volumio systemd[1]: mpd.service start request repeated too quickly, refusing to start.
Sep 21 12:28:08 volumio systemd[1]: Failed to start Music Player Daemon.
```
Research led me to [this](https://community.volumio.org/t/mpd-broken-in-volumio-2-5-26/9774) and after a reboot I was back up and running:
```
volumio@volumio:~$ sudo systemctl status mpd.service -l
● mpd.service - Music Player Daemon
   Loaded: loaded (/lib/systemd/system/mpd.service; enabled)
   Active: active (running) since Mon 2020-09-21 12:45:49 PDT; 1min 12s ago
     Docs: man:mpd(1)
           man:mpd.conf(5)
 Main PID: 727 (mpd)
   CGroup: /system.slice/mpd.service
           └─727 /usr/bin/mpd --no-daemon

Sep 21 12:45:46 volumio systemd[1]: Starting Music Player Daemon...
Sep 21 12:45:49 volumio systemd[1]: Started Music Player Daemon.
```
Not sure how that broke but at least I can now install and see what happens

**Comment by GeorgeIoak** [comment]
OK, back up and running! I'll close this and open a new issue if I have questions about the new configuration
