### ISSUE TITLE
Wrong Colors on ssd1351 waveshare

### ISSUE THREAD

**Issue by avjui** [Maschine2501/NR1-UI#10]
I have wrong Colors with the 1.5" Oled ssd1351 from waveshare.

One fix for me is to add 'bgr=True'  option to line 278.
from
https://github.com/Maschine2501/NR1-UI/blob/1c2ad0606ef79f0903dae070a36ad6462447f4a4/nr1ui.py#L278
to
```
oled = ssd1351(interface, rotate=oledrotation, bgr=True)  
```

**Comment by Maschine2501** [comment]
Hi avjui, thank you for your report.
I will implement a feature in the installation, where the user can select if he has a RGB or BGR display...
Until this is implemented this Issue remains open.
Cheers :)

**Comment by Maschine2501** [comment]
I've set this to the Wish- / ToDo-List :)
