### ISSUE TITLE
Problem with oled ssd1306

### ISSUE THREAD

**Issue by klimma1508** [Maschine2501/NR1-UI#11]
Hello, I tried to install this addon, but it cant start. It writes error with library requests. I tried to install that library with pip, but it didn't help. Where do I make mistakes? Thank you Klimš
![image](https://user-images.githubusercontent.com/55253868/147877546-be98a68b-40de-473a-8829-20404d3d2af6.png)

**Comment by GeorgeIoak** [comment]
It seems as though Python requests module did not get installed for you for some reason. You can try to install it manually if that was the only issue during the install. If you are running the new Buster version you would type:

`sudo pip3 install requests`

or if you are running volumio2 you would enter

`sudo /home/volumio/src/Python-3.8.5/bin/pip3.8 install requests`

It seems starnge if that is your only issue so if you get errors after installing the requests module you probably should run through the install scripts again.

**Comment by Maschine2501** [comment]
@GeorgeIoak Thanks for your support!!!
@klimma1508 Please do a clean installation of newest volumio and a clean NR1-UI installation after that... This kind of Issue should be gone :)
