### ISSUE TITLE
Problem with oled st7735

### ISSUE THREAD

**Issue by dorinik** [Maschine2501/NR1-UI#12]
Hello!
First of all, congratulations and thanks for your work !
I tried the ssd1306 display, which works fine, and then I tried the st7735 but it doesn't display anything - just the backlight.
I mention that the st7735 display works perfectly in another project.

Please select your SPI / I2C Display-Type.
_______________________
Valid selections are:
1 -> for ssd1306
2 -> for ssd1322
3 -> for Braun-specific
4 -> for ssd1351
5 -> for st7735
--->
Enter your decision: 5
Set Display-Type as st7735

volumio @ volumio-joyit: ~ $ sudo journalctl -fu nr1uibuster.service
- Logs begin at Thu 2019-02-14 12:11:59 EET. -
Apr 08 18:08:20 volumio-joyit nr1ui [518]: CAVA1 Fifo-Output is present in mpd.conf
Apr 08 18:08:20 volumio-joyit nr1ui [518]: CAVA2 Fifo-Output is present in mpd.conf
Apr 08 18:08:20 volumio-joyit nr1ui [518]: Layout selected during setup: No-Spectrum
Apr 08 18:08:20 volumio-joyit nr1ui [518]: Last manually selected Layout: No-Spectrum
Apr 08 18:08:20 volumio-joyit nr1ui [518]: Traceback (most recent call last):
Apr 08 18:08:20 volumio-joyit nr1ui [518]: File "/home/volumio/NR1-UI/nr1ui.py", line 237, in <module>
Apr 08 18:08:20 volumio-joyit nr1ui [518]: from luma.lcd.device import st7735
Apr 08 18:08:20 volumio-joyit nr1ui [518]: ModuleNotFoundError: No module named 'luma.lcd'
Apr 08 18:08:20 volumio-joyit systemd [1]: nr1uibuster.service: Main process exited, code = exited, status = 1 / FAILURE
Apr 08 18:08:20 volumio-joyit systemd [1]: nr1uibuster.service: Failed with result 'exit-code'.

**Comment by Maschine2501** [comment]
Hi thanks, for your report!
Looks like your installation is missing the "luma.lcd" module (Apr 08 18:08:20 volumio-joyit nr1ui [518]: ModuleNotFoundError: No module named 'luma.lcd').
I checked it with my (clean) installation, my luma.lcd module is there...
could you please run this command and post your result here?
`pip list`

Should look like this:
`volumio@volumio:~$ pip list
Package          Version
---------------- -----------
asn1crypto       0.24.0
cbor2            5.4.2.post1
certifi          2018.8.24
cffi             1.15.0
chardet          3.0.4
colorzero        2.0
cryptography     2.6.1
Deprecated       1.2.13
entrypoints      0.3
gpiozero         1.6.2
idna             2.6
keyring          17.1.1
keyrings.alt     3.1.1
luma.core        2.3.1
luma.lcd         2.9.0
luma.oled        3.8.1
numpy            1.21.5
pcf8574          0.1.3
Pillow           9.0.1
pip              22.0.4
psutil           5.9.0
pycparser        2.21
pycrypto         2.6.1
pycurl           7.45.1
pyftdi           0.54.0
PyGObject        3.30.4
pyserial         3.5
pyusb            1.2.1
pyxdg            0.25
readchar         3.0.5
requests         2.21.0
RPi.GPIO         0.7.1
SecretStorage    2.3.1
setuptools       61.1.1
six              1.12.0
smbus-cffi       0.5.1
smbus2           0.4.1
socketIO-client  0.7.2
spidev           3.5
urllib3          1.24.1
websocket-client 1.3.1
wheel            0.37.1
wrapt            1.14.0
`

**Comment by dorinik** [comment]
Hello Maschine2501,
I fixed the problem with: sudo -H pip install --upgrade luma.lcd
In fact, it is a partial fix, because, after a day of normal operation, the next day, at startup, I have the same bright screen ...
Now fixed with:
sudo systemctl stop nr1uibuster.service
sudo systemctl start nr1uibuster.service
I mention that at ssd1306 I don't have this problem!
Now I do a clean install on another SD card and come back with the results for the pip list

Best Regards!

**Comment by dorinik** [comment]
Hello Maschine2501,
It seems that everything is fine after the latest changes, at least for the st7735 display.
I did 4 or 5 clean installations and it worked every time.
Sometimes it happens that after the reboot or shutdown, the white screen appears again, but it is solved with:
sudo systemctl stop nr1uibuster.service
sudo systemctl start nr1uibuster.service
Thanks again for your hard work and good health!
Best Regards!

**Comment by Maschine2501** [comment]
Hi Dorinik,
thanks for your feedback :)
