### ISSUE TITLE
No Spectrum Still Displays Spectrum

### ISSUE THREAD

**Issue by GeorgeIoak** [Maschine2501/NR1-UI#2]
When I initially ran the configuration script I choose No Spectrum but the display showed the spectrum on the left. When I checked `/home/volumio/NR1-UI/ConfigurationFiles/LayoutSet.txt` it had (I think) VU-Meter so I manually changed it to No-Spectrum and rebooted but I'm still seeing the spectrum. I ran through the configuration script again and verified that `/home/volumio/NR1-UI/ConfigurationFiles/LayoutSet.txt` still had No-Spectrum.

When I look in `/home/volumio/NR1-UI/ConfigurationFiles/PreConfiguration.py` I see:

```
#config for Display:
DisplayTechnology = "spi1322"
NowPlayingLayout ='Spectrum-Left'
oledrotation = 0
```
So I manually edited `/home/volumio/NR1-UI/ConfigurationFiles/PreConfiguration.py` to use `No-Spectrum` and that successfully removed the spectrum after restarting the service.

- Also I noticed a minor typo in `PreConfiguration.sh`, [Line 180](https://github.com/Maschine2501/NR1-UI/blob/master/PreConfiguration.sh#L180) should be rotated instead of rotaded
- It would be nice to allow choosing the address of your PCF8574/A since there are many options and if the PCF isn't found at address 0x20 the service stops running

**Comment by Maschine2501** [comment]
At the moment I have no idea, why it was not set to "NO-Spectrum"  -> I'll investigate that later...

The Option to chose the adress of the PCF8574/A is a good Idea! Can you provide me the possible adresses?

* fixed typo in Line180 and also in install38conf.sh

**Comment by GeorgeIoak** [comment]
I happen to be using a [NXP PCF8574A](https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf). You can see on pages 5 and 6 that depending on how the address pins are wired you can have an address from 0x20-0x27 for the PCF8574 and addresses 0x38-0x3F for the PCF8574A. The TI parts use the same addresses as well.

**Comment by Maschine2501** [comment]
...changed Headline.

The "No-Spectrum" (nowPlayingLayout)- Bug shouldbe fixed. (was a missing "space" in front of the value...)

The Typo was fixed.

Regarding the adress-selection for PCFxxxx -> I'm working on that ;)

**Comment by Maschine2501** [comment]
@GeorgeIoak I've made a script to configure the I2C adress.
Maybe you can give it a try? 
Right now I'm not sure if i'll put it in the main installation...

[Here is the script](https://github.com/Maschine2501/NR1-UI/blob/master/pcf-i2c-adress-config.sh)

```
sudo chmod +x pcf-i2c-adress-config.sh

bash pcf-i2c-adress-config.sh
```

**Comment by Maschine2501** [comment]
Implemented the "script to configure the I2C adress" in main installation-script.
