### ISSUE TITLE
Don't Overwrite /boot/config.txt

### ISSUE THREAD

**Issue by GeorgeIoak** [Maschine2501/NR1-UI#4]
Rather than overwrite `config.txt` any additions or changes should be added to `/boot/userconfig.txt` because there may be changes in `config.txt` that the user added which shouldn't be overwritten.

**Comment by Maschine2501** [comment]
Good idea!
I think i'll change it... additionally I'll implement a dialog for each setting: "Internal Bluetooth", "Internal Wifi" and "Touchscreen" -> so that only the choice of the user will be written to userconfig.txt...

**Comment by GeorgeIoak** [comment]
That would be good. Right now I think you always write in `dtoverlay=gpio-shutdown` even though your script asks if you don't have the shutdown circuit.

**Comment by Maschine2501** [comment]
@GeorgeIoak I just cleaned up a bit... (moved the python 3.5.2 version to a new repository) 
After that I implemented 3 new configuration options at the beginning of the installation script:
* use of internal Bluetooth
* use of internal WiFi
* Support for Touchscreen
-> all this is written to userconfig.txt

The "dtoverlay=gpio-shutdown" - Value is now related to the choice if the Standby Circuit is used. And will only be written to userconfig.txt if Standby is selected.

...I'm running the "new" installation script at the moment... I hope everything runs smooth, so i guess this "issue" is fixed ;)

**Comment by Maschine2501** [comment]
Test succesfull. -> Closed.
