### ISSUE TITLE
Minor Typos in install.sh

### ISSUE THREAD

**Issue by GeorgeIoak** [Maschine2501/NR1-UI#5]
Going through a clean new install today and noticed some very minor typos:

- https://github.com/Maschine2501/NR1-UI/blob/master/install.sh#L360 "Specrum" is misspelled in several echo statements
- https://github.com/Maschine2501/NR1-UI/blob/master/install.sh#L607 Error message display valid GPIO numbers as 0-26 instead of 0-27

**Comment by Maschine2501** [comment]
Thanks for reporting, fixed this  ;)
