### ISSUE TITLE
Powermanagement with ATtiny85

### ISSUE THREAD

**Issue by rudiratlos** [Maschine2501/NR1-UI#6]
Hi,
your projects looks great, maybe you are interessted in my project:
[https://github.com/rudiratlos/RPI_PowerMgmt](url)
instead of your Attiny85 project.

**Comment by Maschine2501** [comment]
Hi!
Thank you ;)
I've had a look @ your project. Looks pretty cool.
If I'll use it, i would defenetly change some behaviors, remove LED's...
But maybe it is a good alternative for the users of my code...
I'll paste a link to your project in my wiki!
Thanks for sharing!


[Link to Wiki](https://github.com/Maschine2501/NR1-UI/wiki/Standby-Module)
